version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - amazon-linux-extras enable docker
      - yum install -y docker
      - service docker start

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 755694651723.dkr.ecr.us-west-2.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t project-app-container .
      - docker tag project-app-container:latest 755694651723.dkr.ecr.us-west-2.amazonaws.com/project-app-container:latest

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push 755694651723.dkr.ecr.us-west-2.amazonaws.com/project-app-container
      - echo "Build completed successfully"
